"""Export and delivery utilities for compliance reports."""

import os
import smtplib
import requests
from pathlib import Path
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders
from datetime import datetime

from src.config.settings import OUTPUT_DIR


def export_to_pdf(markdown_path: str = None, output_path: str = None) -> str:
    """
    Convert markdown report to PDF.
    
    Args:
        markdown_path: Path to markdown file (default: output/compliance_report.md)
        output_path: Path for PDF output (default: output/compliance_report.pdf)
    
    Returns:
        Path to generated PDF
    """
    try:
        from fpdf import FPDF
    except ImportError:
        raise ImportError("PDF export requires: pip install fpdf2")
    
    markdown_path = markdown_path or OUTPUT_DIR / "compliance_report.md"
    output_path = output_path or OUTPUT_DIR / "compliance_report.pdf"
    
    # Read markdown
    with open(markdown_path, "r", encoding="utf-8") as f:
        md_content = f.read()
    
    # Create PDF
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 15, "Compliance Analysis Report", ln=True, align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 10, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align="C")
    pdf.ln(10)
    
    # Content
    pdf.set_font("Helvetica", "", 11)
    
    for line in md_content.split('\n'):
        # Handle headers
        if line.startswith('# '):
            pdf.ln(5)
            pdf.set_font("Helvetica", "B", 16)
            pdf.multi_cell(0, 8, line[2:])
            pdf.set_font("Helvetica", "", 11)
        elif line.startswith('## '):
            pdf.ln(5)
            pdf.set_font("Helvetica", "B", 14)
            pdf.multi_cell(0, 7, line[3:])
            pdf.set_font("Helvetica", "", 11)
        elif line.startswith('### '):
            pdf.ln(3)
            pdf.set_font("Helvetica", "B", 12)
            pdf.multi_cell(0, 6, line[4:])
            pdf.set_font("Helvetica", "", 11)
        elif line.startswith('- ') or line.startswith('* '):
            pdf.multi_cell(0, 6, f"  • {line[2:]}")
        elif line.startswith('**') and line.endswith('**'):
            pdf.set_font("Helvetica", "B", 11)
            pdf.multi_cell(0, 6, line.strip('*'))
            pdf.set_font("Helvetica", "", 11)
        elif line.strip():
            # Clean up markdown formatting
            clean_line = line.replace('**', '').replace('*', '').replace('`', '')
            pdf.multi_cell(0, 6, clean_line)
        else:
            pdf.ln(3)
    
    # Footer
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 10, "Generated by Policy Documents Agentic AI Application", align="C")
    
    # Save
    pdf.output(str(output_path))
    
    return str(output_path)


def send_to_telegram(
    file_path: str,
    bot_token: str = None,
    chat_id: str = None,
    caption: str = "📋 Compliance Report"
) -> bool:
    """
    Send file to Telegram.
    
    Args:
        file_path: Path to file to send
        bot_token: Telegram bot token (or set TELEGRAM_BOT_TOKEN env var)
        chat_id: Telegram chat ID (or set TELEGRAM_CHAT_ID env var)
        caption: Message caption
    
    Returns:
        True if successful
    """
    bot_token = bot_token or os.getenv("TELEGRAM_BOT_TOKEN")
    chat_id = chat_id or os.getenv("TELEGRAM_CHAT_ID")
    
    if not bot_token or not chat_id:
        raise ValueError(
            "Telegram credentials required. Set TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID in .env"
        )
    
    url = f"https://api.telegram.org/bot{bot_token}/sendDocument"
    
    with open(file_path, "rb") as f:
        response = requests.post(
            url,
            data={"chat_id": chat_id, "caption": caption},
            files={"document": f}
        )
    
    if response.status_code == 200:
        print(f"✅ Report sent to Telegram!")
        return True
    else:
        print(f"❌ Telegram send failed: {response.text}")
        return False


def send_to_email(
    file_path: str,
    to_email: str = None,
    subject: str = "📋 Compliance Analysis Report",
    body: str = "Please find attached the compliance analysis report.",
    smtp_server: str = None,
    smtp_port: int = 587,
    smtp_user: str = None,
    smtp_password: str = None,
) -> bool:
    """
    Send file via email.
    
    Args:
        file_path: Path to file to attach
        to_email: Recipient email (or set REPORT_EMAIL env var)
        subject: Email subject
        body: Email body
        smtp_server: SMTP server (or set SMTP_SERVER env var)
        smtp_port: SMTP port (default 587)
        smtp_user: SMTP username (or set SMTP_USER env var)
        smtp_password: SMTP password (or set SMTP_PASSWORD env var)
    
    Returns:
        True if successful
    """
    to_email = to_email or os.getenv("REPORT_EMAIL")
    smtp_server = smtp_server or os.getenv("SMTP_SERVER", "smtp.gmail.com")
    smtp_user = smtp_user or os.getenv("SMTP_USER")
    smtp_password = smtp_password or os.getenv("SMTP_PASSWORD")
    
    if not all([to_email, smtp_user, smtp_password]):
        raise ValueError(
            "Email credentials required. Set REPORT_EMAIL, SMTP_USER, SMTP_PASSWORD in .env"
        )
    
    # Create message
    msg = MIMEMultipart()
    msg['From'] = smtp_user
    msg['To'] = to_email
    msg['Subject'] = subject
    
    msg.attach(MIMEText(body, 'plain'))
    
    # Attach file
    with open(file_path, "rb") as f:
        part = MIMEBase('application', 'octet-stream')
        part.set_payload(f.read())
        encoders.encode_base64(part)
        part.add_header(
            'Content-Disposition',
            f'attachment; filename="{Path(file_path).name}"'
        )
        msg.attach(part)
    
    # Send
    try:
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_password)
            server.send_message(msg)
        print(f"✅ Report sent to {to_email}!")
        return True
    except Exception as e:
        print(f"❌ Email send failed: {e}")
        return False
